import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sfProRounded = localFont({
  src: [
    {
      path: "./fonts/SF-Pro-Rounded-Light.otf",
      weight: "200",
      style: "light",
    },
    {
      path: "./fonts/SF-Pro-Rounded-Regular.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Rounded-Medium.otf",
      weight: "600",
      style: "medium",
    },
    {
      path: "./fonts/SF-Pro-Rounded-Semibold.otf",
      weight: "700",
      style: "semi-bold",
    },
    {
      path: "./fonts/SF-Pro-Rounded-Bold.otf",
      weight: "800",
      style: "bold",
    },
    {
      path: "./fonts/SF-Pro-Rounded-Heavy.otf",
      weight: "900",
      style: "black",
    },
  ],
  variable: "--font-sf-pro-rounded"
})

const sfPro = localFont({
  src: [
    {
      path: "./fonts/SF-Pro-Text-Light.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Text-LightItalic.otf",
      weight: "200",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Text-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Text-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Text-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Text-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Text-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Text-SemiboldItalic.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Text-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Text-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Text-Heavy.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Text-HeavyItalic.otf",
      weight: "800",
      style: "italic",
    }
  ],
  variable: "--font-sf-pro"
})

export const metadata: Metadata = {
  title: "AQMS - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfPro.variable} ${sfProRounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
